### PR TITLE
Fix for #1775 and #1760 

### LINKED ISSUE #1775: [Dynamic Form] Always Show Required Field Validation Error In "FormDisplayMode.Edit" Mode
#### Category
[ ] Enhancement

[x] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [ 3.17  ]. It works well in [3.16] 
Dynamic Form refactored a lot in 3.17 

#### Expected / Desired Behavior / Question
Ideally when you edit an existing item with "Dynamic Form", it should not show "You can't leave this blank." error if this field already has data.

#### Observed Behavior
When in Edit mode (PageType=6), Dynamic Form control will always show "You can't leave this blank." error on required field even it already has existing data on current item. 
image

#### Steps to Reproduce
1. Choose a list which has a required field (e.g. title) and create a new item. Make sure this new created item has data on required field.
2. Put "Dynamic Form" in the spfx form customization, no special settings.

```
     <DynamicForm
          context={this.props.context}
          listId={this.props.context.list.guid.toString()}
          listItemId={this.props.context.itemId}
          onSubmitted={(listItemData: any) => {
            console.log(listItemData);       
              setTimeout(() => {
                this.props.onSave();
              }, 1000);
          }} 
          onListItemLoaded={async (listItemData: any) => { // eslint-disable-line @typescript-eslint/no-explicit-any
            console.log(listItemData);
          }} />
```
3.  Update EditForm Config in "serve.json" to point to this new created item, then launch it with edit form config
image

4. You will see "You can't leave this blank." error on this item even it already has data on this field
image

### PR DESCRIPTION
**Pull request by wuxiaojun514**
| Q               | A
| --------------- | ---
| Bug fix?        | [ x]
| New feature?    | [ ]
| New sample?      | [ ]
| Related issues?  | fixes #1775 #1760 

#### What's in this Pull Request?

This pull request is to fix two issues on required field validation issues in **Dynamic Form** control
**Dynamic Form** has done huge refactoring on version 3.17. See [pull request 1672](https://github.com/pnp/sp-dev-fx-controls-react/pull/1672) for detail

The root cause of issue #1760 is due to the initial value of `newValue`  has been changed from "null" to "undefined". So I modified  the related code to "undefined" as well.

Regarding #1775 , now `changedValue` won't use loaded item's value as initial value.  So I added another check to compare with `value` when there is no new value on this field.

### CODE REVIEW

**Comment by 6gal6ler6** [comment]
@wuxiaojun514 

Thanks for taking care of this issue!!!

**Comment by devspfx** [comment]
When will be this fix available? When we will have a new release?

**Comment by joelfmrodrigues** [comment]
Waiting for #1726

**Comment by devspfx** [comment]
@joelfmrodrigues any news about this issue? We hope to have a resolution

**Comment by martinlingstuyl** [comment]
> Waiting for #1726

Hi @joelfmrodrigues, why is this PR dependant on the #1726? It seems to be unrelated: editing filenames versus required fields showing a message.

It would be nice if we could ditch the dependency and get this fixed soon. (I've got customers running into this as well...) If I can help with any of this, do let me know!

**Comment by joelfmrodrigues** [comment]
Hey @martinlingstuyl I will have a look and likely merge this one as the other PR has unresolved conflicts for a long time. I haven't been active for a while for personal reasons (new kid and too much work 😅) but trying to get my head back into this and will try to look into this later today or over the weekend

**Comment by martinlingstuyl** [comment]
Great to hear @joelfmrodrigues! Yeah, personal reasons enough that can lower your available time in open source. also on my end recently. I know how it goes 😀 

Do let me know if I can be of help...

**Comment by joelfmrodrigues** [comment]
@wuxiaojun514 This is now merged. I'm really sorry for the time it took to merge
Thanks for the great work and clean code change

**Comment by joelfmrodrigues** [comment]
@6gal6ler6 @devspfx @martinlingstuyl  this is now merged, apologies for the delay

**Comment by martinlingstuyl** [comment]
That's great to hear @joelfmrodrigues! My customer is going to be super excited 😀 

What's the release date for 3.20?

**Comment by joelfmrodrigues** [comment]
@martinlingstuyl no date scheduled yet, but I will start the discussion on this as I can see there are several fixes/improvements already in this beta

**Comment by martinlingstuyl** [comment]
Maybe I can fix the PR assigned to me first.😊 I'll see if I can make haste there

**Comment by martinlingstuyl** [comment]
Hi @joelfmrodrigues,

I now see why you related this pr to #1726: 

The testform now only works if I include FileLeafRef in the hiddenFields array. If I do not do that, submitting the form fails without an error. (due to the fact that the dynamic form currently cannot render `File` type Fields.

What I'm now using in TestForm.tsx:

```tsx
<DynamicForm
          context={this.props.context}
          contentTypeId='0x0120D52000796BC7FCC8B819488729FB2B77B0E799002B2379630DCCB04D883603B763E843D7'
          listId={this.props.context.list.guid.toString()}
          listItemId={this.props.context.itemId}
          hiddenFields={['FileLeafRef']}
          onListItemLoaded={async (listItemData: any) => { // eslint-disable-line @typescript-eslint/no-explicit-any
            console.log(listItemData);
          }} />
```

FYI

**Comment by 6gal6ler6** [comment]
Will the branch conflicts of #1726 be resolved?

I see that @gruizdev is not responsive on that PR

**Comment by joelfmrodrigues** [comment]
> Hi @joelfmrodrigues,
> 
> I now see why you related this pr to #1726:
> 
> The testform now only works if I include FileLeafRef in the hiddenFields array. If I do not do that, submitting the form fails without an error. (due to the fact that the dynamic form currently cannot render `File` type Fields.
> 
> What I'm now using in TestForm.tsx:
> 
> ```tsx
> <DynamicForm
>           context={this.props.context}
>           contentTypeId='0x0120D52000796BC7FCC8B819488729FB2B77B0E799002B2379630DCCB04D883603B763E843D7'
>           listId={this.props.context.list.guid.toString()}
>           listItemId={this.props.context.itemId}
>           hiddenFields={['FileLeafRef']}
>           onListItemLoaded={async (listItemData: any) => { // eslint-disable-line @typescript-eslint/no-explicit-any
>             console.log(listItemData);
>           }} />
> ```
> 
> FYI

Ouch, I missed this, thanks for reporting back

**Pull request merged**
