### PR TITLE
Added ListItemComments component to Controls.tsx

### PR DESCRIPTION
**Pull request by NishkalankBezawada**
| Q               | A
| --------------- | ---
| Bug fix?        | [ ]
| New feature?    | [ ]
| New sample?      | [ ]
| Related issues?  | fixes #X, partially #Y, mentioned in #Z

#### What's in this Pull Request?
Added ```ListItemComments``` component to ```Controls.tsx```

Thanks,
Nishkalank

### CODE REVIEW

**Comment by joaojmendes** [comment]
Hi, @NishkalankBezawada. Thank you for your PR, Please can you resolve the conflicts?

**Comment by NishkalankBezawada** [comment]
> Hi, @NishkalankBezawada. Thank you for your PR, Please can you resolve the conflicts?

Hey @joaojmendes 

I have just resolved the conflicts. 

Thanks,
Nishkalank

**Comment by joelfmrodrigues** [comment]
Many thanks @NishkalankBezawada , merged

**Comment by NishkalankBezawada** [comment]
> Many thanks @NishkalankBezawada , merged

Thanks @joelfmrodrigues

**Pull request merged**
