### PR TITLE
Added the ability to the TreeView component to expand the nodes to see defaultSelectedKeys.

### LINKED ISSUE #559: TreeView: Expand to selected
#### Category
- [x] Enhancement
- [ ] Bug
- [ ] Question

#### Version

Please specify what version of the library you are using: [1.18.0]

Add ability to the `TreeView` component to expand the nodes to see `defaultSelectedKeys`.
For example, add `expandToSelected: boolean` property to the component.

### PR DESCRIPTION
**Pull request by siddharth-vaghasia**
| Q               | A
| --------------- | ---
| New feature?    | [ X]

| Related issues?  | fixes #559 

#### What's in this Pull Request?

Added the ability to the TreeView component to expand the nodes to see defaultSelectedKeys.
For example, add expandToSelected: boolean property to the component. 

Note - This PR also includes changes for issue #560 and #561 which @nanddeepn have fixed and submitted separate PR for the same(yet not merged or approved).  Not sure whether I did the right thing to include these changes in this PR but to test scenarios for my changes I need these changes here also.  If not, please advise.

### CODE REVIEW

**Comment by AJIXuMuK** [comment]
Hi @siddharth-vaghasia!
Thank you for the changes!
I did small updates and merged both your and @nanddeepn PRs.

**Comment by siddharth-vaghasia** [comment]
thanks @AJIXuMuK .... on another note, do you think this control will be useful in Property pane repo? We were thinking if there are valid use case, we can work on it...just wanted to know your view.

**Comment by AJIXuMuK** [comment]
@siddharth-vaghasia  - I think there might be scenarios where tree view could be used in the property pane... something like displaying documents with folder hierarchy, custom hierarchical filter, or displaying Teams and underlying Channels. 
But you need to keep in mind that all of those scenarios have different `data` under each tree item. 

We can also create a “question” in the repo to see if people are really interested in such control as I don’t want you to waste your time :)

**Comment by siddharth-vaghasia** [comment]
@AJIXuMuK ...thanks..make sense.. will create a question in property pane repo to see if people are interested..!!

**Pull request merged**
