### PR TITLE
Added allowTextInput property

### PR DESCRIPTION
**Pull request by milanholemans**
| Q               | A
| --------------- | ---
| Bug fix?        | [ ]
| New feature?    | [ x ]
| New sample?      | [ ]
| Related issues?  | fixes [#1094](https://github.com/pnp/sp-dev-fx-controls-react/issues/1094)

#### What's in this Pull Request?

Exposed the allowTextInput property. Developer can now choose whether the user can add dates as text value rather than picking one from the date picker.

### CODE REVIEW

**Comment by joelfmrodrigues** [comment]
@milanholemans many thanks for the PR. I just noticed that the previous default value was `true` and now is `false` so wondering if this could cause issues to people who upgrade and don't notice the change. Could this be set to `true` by default, or did you experience any issues?

**Comment by milanholemans** [comment]
> @milanholemans many thanks for the PR. I just noticed that the previous default value was `true` and now is `false` so wondering if this could cause issues to people who upgrade and don't notice the change. Could this be set to `true` by default, or did you experience any issues?

The thing is, I noticed that the DatePicker component of office-fabric-ui uses `false` as default value. That's why I made it false here by default as well. I can change it to `true` if needed.

**Comment by joelfmrodrigues** [comment]
@AJIXuMuK what are your thoughts regarding changing this default value? Should we avoid it or go ahead and ensure that it's documented/announced?

**Comment by milanholemans** [comment]
It has been changed from `false` to `true` last year, check this PR [#971](https://github.com/pnp/sp-dev-fx-controls-react/pull/971).

**Comment by AJIXuMuK** [comment]
@joelfmrodrigues I would not change the defaults without a necessity. 
@milanholemans - thank you for providing this info. 
This is our mistake. We should have implemented this as property right away. 
But for now - let's leave the default as is.

**Comment by milanholemans** [comment]
@AJIXuMuK @joelfmrodrigues I changed the default value to `true`.

**Comment by joelfmrodrigues** [comment]
@milanholemans many thanks, it has now been merged

**Pull request merged**
