### PR TITLE
Updating development environment

### PR DESCRIPTION
**Pull request by michaelmaillot**
| Q               | A
| --------------- | ---
| Bug fix?        | [ ]
| New feature?    | [x]
| New sample?      | [ ]
| Related issues?  | mentioned in #1410

#### What's in this Pull Request?

This PR includes new SPFx extensions (app customizer & form customizer) in order to test the controls locally. It also includes documentation update regarding MPA.

### CODE REVIEW

**Comment by joelfmrodrigues** [comment]
@michaelmaillot really sorry for the delay in reviewing this. There was a very large PR with a new control that I wanted to complete first to avoid conflicts on the test web part and components :)
Your PR is now having a conflict with a recent update to the yo-rc file. Could you please pull from the dev branch and update the PR?

**Comment by joelfmrodrigues** [comment]
@michaelmaillot sorry ignore my last message, I have resolved it

**Comment by joelfmrodrigues** [comment]
> @michaelmaillot sorry ignore my last message, I have resolved it

@michaelmaillot sorry ignore my last message, I have resolved it

**Comment by joaojmendes** [comment]
@michaelmaillot  Thank you for the changes !

**Pull request merged**
