### PR TITLE
calendar restricted dates

### PR DESCRIPTION
**Pull request by srpmtt**
| Q               | A
| --------------- | ---
| Bug fix?        | [ ]
| New feature?    | [X]
| New sample?      | [ ]
| Related issues?  | mentioned in #516 

#### What's in this Pull Request?

Disable specific dates from DateTimePicker calendar.

### CODE REVIEW

**Comment by joelfmrodrigues** [comment]
@srpmtt many thanks for the PR! I had a quick look and it seems to contain a significant number of changes that are just formatting changes. Could you please discard those when not required as this would simplify the review process significantly?
Also, please get the latest from `dev` branch as there are merge conflicts.

**Comment by joelfmrodrigues** [comment]
The merge conflicts seem to be related to import from @fluentui instead of the old office-ui-fabric equivalent so should be simple to resolve

**Review by joelfmrodrigues — CHANGES_REQUESTED** [review]
Please review comments regarding class names and merge conflicts

**Comment by srpmtt** [comment]
it should be ok now

**Comment by joelfmrodrigues** [comment]
@srpmtt many thanks for the updates, this is now merged.

**Pull request merged**
