### PR TITLE
feat/#958 Add selected items for groups

### PR DESCRIPTION
**Pull request by a1exymoroz**
| Q               | A
| --------------- | ---
| Bug fix?        | [ ]
| New feature?    | [ x ]
| New sample?      | [ ]
| Related issues?  | #958 

#### What's in this Pull Request?

- Description was fixed
- Security group secondary text  returns email of group

### CODE REVIEW

**Comment by gautamdsheth** [comment]
@a1exymoroz - This is a breaking change. So,  could you please modify the PR to make it so that `defaultSelectedUsers` and `defaultSelectedItems` are both supported ? 

If `defaultSelectedUsers` are specified, just append it to `defaultSelectedItems` array internally. 
Once we move to maybe v4, we can remove the `defaultSelectedUsers` property.

**Comment by a1exymoroz** [comment]
> @a1exymoroz - This is a breaking change. So, could you please modify the PR to make it so that `defaultSelectedUsers` and `defaultSelectedItems` are both supported ?
> 
> If `defaultSelectedUsers` are specified, just append it to `defaultSelectedItems` array internally.
> Once we move to maybe v4, we can remove the `defaultSelectedUsers` property.

Ok. I'll change the PR

**Comment by AJIXuMuK** [comment]
Sorry for not looking into this PR earlier.

I don't think we need to provide some new property. Why don't just use `defaultSelectedUsers` as `defaultSelectedItems`?
Yes, the name is not the best one and we can change it in the next major version. But 2 separate properties will bring more confusion.

**Comment by a1exymoroz** [comment]
> Sorry for not looking into this PR earlier.
> 
> I don't think we need to provide some new property. Why don't just use `defaultSelectedUsers` as `defaultSelectedItems`?
> Yes, the name is not the best one and we can change it in the next major version. But 2 separate properties will bring more confusion.

I can revert to the first commit

Actually I need only one changes in 

image

Without this changes I can't set default selected items for security group

**Comment by AJIXuMuK** [comment]
@a1exymoroz - yes, I agree that this change is needed (maybe with modification to check if `element.EntityData` is defined). But I think additional property brings confusion.

**Comment by AJIXuMuK** [comment]
Thank you @a1exymoroz for the change. And sorry for back-and-forth communication!

**Pull request merged**
