### PR TITLE
Added filter for Microsoft 365 Group to PeoplePicker

### PR DESCRIPTION
**Pull request by andreasomayrat**
| Q               | A
| --------------- | ---
| Bug fix?        | [ ]
| New feature?    | [x]
| New sample?      | [ ]
| Related issues?  | 

#### What's in this Pull Request?

Added a filter for Microsoft 365 Group in PeoplePicker

### CODE REVIEW

**Comment by AJIXuMuK** [comment]
Hi @andreasomayrat - thank you for the PR!

Could you please edit a code a bit to use string instead of Guid for the group id?

**Comment by andreasomayrat** [comment]
Hi @AJIXuMuK 
I have now updated the code to use string instead of Guid

**Comment by joelfmrodrigues** [comment]
Changed target branch to dev

**Comment by joelfmrodrigues** [comment]
@andreasomayrat updating documentation to include Directory.Read.All permissions as without it the API call returns users with null properties

**Comment by joelfmrodrigues** [comment]
@andreasomayrat many thanks for the improvements, this has now been merged (I have made only very small adjustments). Will be available in the next release and in the beta version in a few minutes

**Pull request merged**
