### PR TITLE
Sticky header on ListView

### PR DESCRIPTION
**Pull request by Abderahman88**
| Q               | A
| --------------- | ---
| Bug fix?        | [ ]
| New feature?    | [ X]
| New sample?      | [ ]
| Related issues?  | mentioned in #634 

#### What's in this Pull Request?

Added the ability of a fixed header. (https://developer.microsoft.com/en-us/fluentui#/controls/web/scrollablepane)
Both searchbox and headers stay locked during scrolling.

_Property added:_
- stickyHeader (boolean - default false) => Show fixed headers.

_Remarque:_
- Scrollable pane has a fixed height.

sticky_header

### CODE REVIEW

**Comment by AJIXuMuK** [comment]
Thank you @Abderahman88 for the enhancement!
It has been merged with some small changes

**Comment by aaclage** [comment]
Hi @AJIXuMuK, 

This last change also change the height to have a strange behavior, this was expected?

image

**Comment by Abderahman88** [comment]
Hi @aaclage ,

This is (at the moment) the expected behaviour if the stickyHeader-property is set to true.

StickyPropTrue

fixedHeight

If the stickyHeader-property is set to false, it behaves as before.

StickyPropFalse

dynamicHeight

This is a small downside to this feature.

Another possible approach would be adding a pagination-footer.

**Comment by aaclage** [comment]
I am looking that height is max-height=50vh and initially appear with minimal and only grow to the max.

**Comment by aaclage** [comment]
@Abderahman88 
Follow up PR #696

**Comment by Abderahman88** [comment]
Nice work! @aaclage

**Pull request merged**
