### PR TITLE
Module not found - Wrong @fluentui imports cause webpack build errors #1763

### LINKED ISSUE #1763: Module not found - Wrong @fluentui imports cause webpack build errors
#### Category
[ ] Enhancement

[X ] Bug

[ ] Question

#### Version
Version: 3.17.0

#### Expected / Desired Behavior / Question
We are using the spfx-controls-react within a webpack project and would expect to build it without webpack errors.

#### Observed Behavior
We are using the spfx-controls-react within a webpack project. When we build the project we get several webpack errors like:
image

#### Steps to Reproduce
We could identify the used imports of the @fluentui package to cause that issue:
You are using for example the following import: 
`import { ActionButton, PrimaryButton } from "@fluentui/react/lib/components/Button";`
The correct import would be:
`import { PrimaryButton } from '@fluentui/react/lib/Button';`
as described on the [fluent ui page](https://developer.microsoft.com/en-us/fluentui#/controls/web/button)

You can also check the export section of the @fluentui package.json file.
There for example the button is declared as
```
"./lib/Button": {
      "types": "./lib/Button.d.ts",
      "import": "./lib/Button.js",
      "require": "./lib-commonjs/Button.js"
    },
```
so without the /components/ section of the import you are using.

For testing we fixed the wrong imports in the following files and that fixed all build errors we got
image

Could you please check all your imports of the @fluentui package?

Thanks
Pascal

### PR DESCRIPTION
**Pull request by raclettierer**
| Q               | A
| --------------- | ---
| Bug fix?        | [ x]
| New feature?    | [ ]
| New sample?      | [ ]
| Related issues?  | fixes #1763

#### What's in this Pull Request?

(https://github.com/pnp/sp-dev-fx-controls-react/issues/1763)

### CODE REVIEW

**Comment by joelfmrodrigues** [comment]
@raclettierer I'm sorry for the delay on this, has been flagged on my inbox as to-do since you created the PR, but I was busy with the release of a baby 😄
We will try to review soon

**Comment by joelfmrodrigues** [comment]
@raclettierer I have updated the target branch to the `dev` branch. Can you please get the latest version from dev and resolve the conflicts on the PR?

**Comment by raclettierer** [comment]
@joelfmrodrigues  :  done

**Comment by joelfmrodrigues** [comment]
@raclettierer many thanks, this is now merged

**Pull request merged**
