### PR TITLE
Add Accordion control from https://github.com/hugoabernier/AccordionWebPart

### PR DESCRIPTION
**Pull request by sadomovalex**
| Q               | A
| --------------- | ---
| Bug fix?        | [ ]
| New feature?    | [x ]
| New sample?      | [ ]
| Related issues?  | fixes #X, partially #Y, mentioned in #Z

#### What's in this Pull Request?

Add Accordion control from https://github.com/hugoabernier/AccordionWebPart

### CODE REVIEW

**Comment by estruyf** [comment]
@AJIXuMuK it is because of the dependency of Office UI Fabric 6.

**Comment by AJIXuMuK** [comment]
@estruyf do you see the reason for that? 
I looked at the code and it seems like it could be based on v5.

**Comment by estruyf** [comment]
Indeed, seems just because the usage of `DefaultButton`.

**Comment by estruyf** [comment]
If we replace that, we can make it happen in `v1`.

**Comment by estruyf** [comment]
ok, seems that it was just a couple of properties that have been renamed. I made changes so that it works fine in v1. Thanks, @sadomovalex for this PR.

**Comment by sadomovalex** [comment]
Great, it is even better!

**Comment by sadomovalex** [comment]
@AJIXuMuK I'm not author of this control. Your thanks should go to @hugoabernier :) I just wanted to make it available with less efforts directly from npm)

**Pull request closed without merging**
