### PR TITLE
fix-typo: AccessibleAccordion

### PR DESCRIPTION
**Pull request by nils-a**
| Q               | A
| --------------- | ---
| Bug fix?        | [ ]
| New feature?    | [ ]
| New sample?      | [ ]
| Related issues?  | none, sorry.

#### What's in this Pull Request?

Fixed a small typo in documentation `docs/documentation/docs/index.md`.

### CODE REVIEW

**Comment by joelfmrodrigues** [comment]
@nils-a many thanks! Merged

**Comment by nils-a** [comment]
@joelfmrodrigues are you certain this was merged? The typo is still there.

**Comment by joelfmrodrigues** [comment]
@nils-a many thanks for the heads up, this is what can happen when I am too tired to work on this 😆 Closed the PR instead of merging it...merged now

**Comment by nils-a** [comment]
Perfect, thanks!

**Pull request merged**
