### PR TITLE
Changed single selection to multiple selection for Recent, OneDrive and Site Files tabs in FilePicker component

### LINKED ISSUE #725: PNP SPFx FilePicker multi select
Hi,

i'm just beginning with react so I will not be doing pull request any time soon.

I have and feature request for enhancement of PNP SPFx FilePicker - would it be possible to add option for multi choice of files?

Thanks

#### Category
[x] Enhancement

[ ] Bug

[ ] Question

#### Expected / Desired Behavior / Question

User is able to check multiple files in library by clicking on the checkbox in front of the filename that is already displayed in latest version of filepicker

Thanks!

### PR DESCRIPTION
**Pull request by MonalisaBaltatescu**
…s for FilePicker component

| Q               | A
| --------------- | ---
| Bug fix?        | [ ]
| New feature?    | [x]
| New sample?      | [ ]
| Related issues?  | fixes #725 

#### What's in this Pull Request?

The current version of the FilePicker doesn't support multiple selections for files.
I have changed the selection mode to multiple for Recent, OneDrive and Site Files tabs. 
The folders cannot be selected but could be opened and multiple selections apply inside.

### CODE REVIEW

**Comment by joelfmrodrigues** [comment]
@MonalisaBaltatescu the PR is for the `master` branch, could you please update to target `dev`?

**Comment by MonalisaBaltatescu** [comment]
@joelfmrodrigues could this PR be closed and merged now that the target branch is master?

**Comment by joelfmrodrigues** [comment]
@MonalisaBaltatescu just tested the PR and it's great! Thank you for the improvements.
While testing it, I found just an error on the console when selecting folders (tested using the Site option):

1. Select a folder from a document library in a SharePoint site
image

2. The following error is logged:
image

3. This is the code generating the error (line 459):
image

Is this line required to handle folders? I tried to comment it and it seems to behave the same, although it could be because of the error not allowing it to behave the same way you expected.

Other than that, all looks good and ready to go ☺️

**Comment by joelfmrodrigues** [comment]
Hi @MonalisaBaltatescu 

just checking if you would be able to advise on the above?

**Comment by MonalisaBaltatescu** [comment]
Hi, I’m working on it. Just need more time ☺️

**Comment by estruyf** [comment]
@MonalisaBaltatescu I have no idea why the PR got closed. Going to re-open it.

**Comment by joelfmrodrigues** [comment]
@MonalisaBaltatescu sorry to chase you again with this, but just wondering if you need some help?

**Comment by MonalisaBaltatescu** [comment]
@joelfmrodrigues I am sorry for the delay, didn't have the time lately. Please check now and let me know if there are any other issues

**Comment by joelfmrodrigues** [comment]
@MonalisaBaltatescu many thanks for the update and absolutely no need to apologise as these are voluntary contributions - I am also having issues finding the time to contribute myself

I have tested it and all seems to be working fine, many thanks

**Pull request merged**
