### PR TITLE
feat(PeoplePicker): add new `allowUnvalidated` option to allow adding non-tenant users

### PR DESCRIPTION
**Pull request by JakeStanger**
Guest users can be identified by the `userUnvalidated` flag.

This is useful for then handling inviting users as guests.

| Q               | A
| --------------- | ---
| Bug fix?        | [ ]
| New feature?    | [x]
| New sample?      | [ ]
| Related issues?  | 

#### What's in this Pull Request?

Adds new prop to the `PeoplePicker` component called `allowUnvalidated`. Setting this to true no longer filters out users which are "unvalidated", which in general means they do not exist in the tenant. This allows the picker to be used for example for an interface to invite guest users.

If a user is unvalidated, the `isUnvalidated` key will be true on the returned object.

### CODE REVIEW

**Review by JakeStanger — COMMENTED** [review]
Good spot, thanks :)

**Comment by joelfmrodrigues** [comment]
Hi @JakeStanger , many thanks for the contribution. The PR has now been merged and changes will be available as part of the next release. You can also test the changes as part of the beta release that will be published automatically in a few minutes.

**Comment by joelfmrodrigues** [comment]
Also, as a side note, I have updated the control docs to include the new property 🙂
Thanks again

**Comment by JakeStanger** [comment]
Ah I completely forgot about docs, thanks!

**Pull request merged**
