### PR TITLE
New feature extension ListView > dragDropFiles V1

### PR DESCRIPTION
**Pull request by aaclage**
| Q               | A
| --------------- | ---
| Bug fix?        | [ ]
| New feature?    | [X]
| New sample?      | [ ]
| Related issues?  | mentioned in #682

#### What's in this Pull Request?
Feature added in V2 #682 and this version is to include in V1 for on premises environments (SP2019) 
This is a new feature extension of ListView control with 2 new properties.
Properties:
dragDropFiles - Specify the drag and drop files area option. Default false.
onDrop - Event handler returns files from drag and drop.

Test Case:
When using ControlsTest.tsx, should retrieve in console the file names.
image

### CODE REVIEW

**Comment by aaclage** [comment]
Hi @AJIXuMuK , 

I don't know if is allow to include new features in v1. if is not possible i can cancel this PR. 
Thank you.

**Comment by AJIXuMuK** [comment]
Hi @aaclage,
Thanks for the PR.

We allow PRs to the v1 as well. The thing is - we're processing them on a low priority basis and don't have some specific plans on next releases.

**Comment by aaclage** [comment]
@AJIXuMuK 

Thank you for your feedback, 
Make sense. i will keep here then.

**Comment by AJIXuMuK** [comment]
This has been merged

**Pull request merged**
