### PR TITLE
#default expanded treeItem

### PR DESCRIPTION
**Pull request by amirmsai**
| Q               | A
| --------------- | ---
| Bug fix?        | [ ]
| New feature?    | [ ]
| New sample?      | [ ]
| Related issues?  | fixes #X, partially #Y, mentioned in #Z

#### What's in this Pull Request?
define the default  expanded items in the tree

#### Guidance
- *You can delete this section when you are submitting the pull request.* 
- *Please update this PR information accordingly. We'll use this as part of our release notes in monthly communications.*
- *Please target your PR to **dev** branch.*

### CODE REVIEW

**Comment by AJIXuMuK** [comment]
Hi @amirmsai - thanks for the PR.
Could you please explain the logic of this property? Especially when it works in combination with `defaultSelectedNodes`.
The final "set" of the expanded node would be an aggregation of the ones from new property and the ones that are expanded because on the selection?

**Comment by amirmsai** [comment]
Hi,
the idea is to use the tree with default Selected Nodes : is to define
the nodes to be expanded.
I use this logic to define the current selected (expanded) node.
For example: i use the tree to manage permission in SPo then i cannot load
all the items (sites, lists, items...), i load only the childs of current
selected item and to manage this scenario it's important to know the
selected item (then to know the item where i have childs).

best regards
Amir MSAI

Le sam. 8 janv. 2022 à 18:42, Alex Terentiev ***@***.***> a
écrit :

**Comment by AJIXuMuK** [comment]
Sorry @amirmsai - could you please provide an example?
Let's say I have some `defaultExpandedKeys` and I also have `expandToSelected` set to `true` and some `defaultSelectedKeys`. What will be the result for the expanded items in the tree? Union? Intersection? or one property will be ignored?

**Comment by AJIXuMuK** [comment]
Thanks @amirmsai!
I will merge the PR and will see how it works in different configurations.

**Comment by amirmsai** [comment]
Hi Alex,

it's very nice :)
Can you please add my name "Amir MSAI" as a contributor ?
Thanks

Le ven. 18 mars 2022 à 20:01, Alex Terentiev ***@***.***> a
écrit :

**Pull request merged**
