### PR TITLE
Patch FieldCollectionData

### PR DESCRIPTION
**Pull request by GuidoZam**
| Q               | A
| --------------- | ---
| Bug fix?        | [ ]
| New feature?    | [ x]
| New sample?      | [ ]

#### What's in this Pull Request?

Added a new implementation for a date field in the FieldCollectionData control.

It also fixes a UI wrong behavior for numeric value that occurs in the FieldCollectionData control when a numeric field is disabled: the input field seems to be editable but it is not.

### CODE REVIEW

**Comment by joelfmrodrigues** [comment]
@GuidoZam many thanks for the updates. There was another PR to the same control that was created before this one and is now merged, adding two new types of controls: combobox and people picker. 
Unfortunately, this resulted in your PR now showing as having conflicts. Could you please get latest changes from dev and resolve the conflicts?

**Comment by GuidoZam** [comment]
@joelfmrodrigues I'll check as soon as I can and let you know.

**Comment by joelfmrodrigues** [comment]
@GuidoZam I ended up resolving the conflicts 🙂 no need to bother

**Comment by joelfmrodrigues** [comment]
@GuidoZam many thanks for the new feature and also the fix. This is now merged into the dev branch

**Comment by GuidoZam** [comment]
@joelfmrodrigues many thanks to you!

**Pull request merged**
