### PR TITLE
Updated ControlsTestWebPart

### PR DESCRIPTION
**Pull request by GuidoZam**
| Q               | A
| --------------- | ---
| Bug fix?        | [ ]
| New feature?    | [ ]
| New sample?      | [ x ]

#### What's in this Pull Request?

Updated the ControlsTestWebPart to show the controls filtered by control type to avoid display everything all at once.

### CODE REVIEW

**Comment by joelfmrodrigues** [comment]
@GuidoZam Many thanks for this! 
There is a PR that was submitted earlier to add a new control that I aim to review before this one as it adds a new control to the page. We will try to get to this one soon

**Comment by joelfmrodrigues** [comment]
@GuidoZam I really like it! So much better than the pile of controls we have at the moment 🤩

image

image

**Comment by joelfmrodrigues** [comment]
Ready to merge, just waiting for #1526 so we can add the new control here as well

**Comment by GuidoZam** [comment]
Thanks @joelfmrodrigues, I'm happy that you like it 😄

**Pull request merged**
