### PR TITLE
PeoplePicker validation bugfix

### PR DESCRIPTION
**Pull request by HardluckHalvey**
Clear error message when onGetErrorMessage() returns empty string

| Q               | A
| --------------- | ---
| Bug fix?        | [X ]
| New feature?    | [X ]
| New sample?      | [ ]
| Related issues?  | fixes #X, partially #Y, mentioned in #Z

#### What's in this Pull Request?

Update to the validate function to handle the props.onGetErrorMessage returning an empty string.  Addresses issue with people picker not clearing error message after passing validation after displaying an error message.

Update to add support for validateOnFocusOut

#### Guidance
- *You can delete this section when you are submitting the pull request.* 
- *Please update this PR information accordingly. We'll use this as part of our release notes in monthly communications.*
- *Please target your PR to **dev** branch.*

### CODE REVIEW

**Comment by joelfmrodrigues** [comment]
@HardluckHalvey many thanks for the great improvements and sorry for the late reply.
I have updated the PR to target the dev branch.

Also, while reviewing and testing, the onBlur change seems to introduce a small issue. When I select users, the on change event returns an array with the selected users; but when I click outside of the field and click back on the field again, the onChange will return an empty array. If I then select another user, it returns again an array with the correct users. It seems to always return an empty array when clicking back on the field. Can you please investigate?

Regarding removing the error message when validation passes, all seems to be working fine.

**Comment by HardluckHalvey** [comment]
Sorry about that - I'll make sure to target any future PRs to target dev.  I'll have a look at the onBlur issue this weekend.  Thanks!

**Comment by HardluckHalvey** [comment]
Hi Joel,

I'm having some trouble with reproducing the issue described - when I utilize the validateOnFocusOut property alongside passing in a method for the onGetErrorMessage property, the PeoplePicker seems to work as intended, only firing the onChange once.  Can you provide an example of how you're calling the PeoplePicker - it will help in my investigation of the PeoplePicker clearing when clicking back into it after entering some data into it.

**Comment by joelfmrodrigues** [comment]
Hi @HardluckHalvey 

Previously I was able to recreate the behaviour I described consistently...this was just by adding the new property to the test controls on the test web part of the solution and it would happen every time following the pattern described. I even saved the changes to test as a stash so I could retest again easily...
Now I just spent a lot of time clicking in and out of people pickers, trying all sorts of things, and I can't recreate it 😅 it's driving me mad 😅 maybe a browser thing, I don't know...

Will approve the PR as it seems to be working fine. Really sorry for the delay

**Pull request merged**
